### ISSUE TITLE
Unity 2023 is invalid

### ISSUE THREAD

**Issue by actforjason** [rostok/UnityToggleTitleBar#1]
> [Package Manager Window] Error adding package: https://github.com/rostok/UnityToggleTitleBar.git.
Unable to add package [https://github.com/rostok/UnityToggleTitleBar.git]:
  Package com.github.rostok.unitytoggletitlebar@https://github.com/rostok/UnityToggleTitleBar.git has invalid dependencies or related test packages:
    com.marijnzwemmer.unity-toolbar-extender (dependency): Version 'https://github.com/marijnz/unity-toolbar-extender.git' is invalid. Expected a 'SemVer' compatible value.
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

**Comment by rostok** [comment]
adding this to dependencies in manifest.json should fix this

```
    "com.marijnzwemmer.unity-toolbar-extender": "https://github.com/marijnz/unity-toolbar-extender.git",
    "com.github.rostok.unitytoggletitlebar": "https://github.com/rostok/UnityToggleTitleBar.git",

```
