### ISSUE TITLE
can't import package with Unity 6

### ISSUE THREAD

**Issue by jeanroukas** [rostok/UnityToggleTitleBar#2]
Hi! Thanks for this useful hack. Unfortunately, I couldn't import it with the package manager of the latest Unity 6 version (6000.0.23f1).

I tried to install it from Git 
// + > install from git > https://github.com/rostok/UnityToggleTitleBar //, 
but nothing happened (just a brief appearance of a new UI that instantly disappeared).

I will try to install it manually, but I wanted to inform you about this issue.

**Comment by jeanroukas** [comment]
- manually import not working also.

- adding this line to Project_Folder/Packages/manifest.json :

_"com.github.rostok.unitytoggletitlebar": "https://github.com/rostok/UnityToggleTitleBar.git",_

**give me this :**
![image](https://github.com/user-attachments/assets/1841f411-14b8-4b19-82af-7f8399ff4c02)

**Comment by jeanroukas** [comment]
OK, so adding those two lines to Project_Folder/Packages/manifest.json fixed my issue. I don't know if it's a bug coming from my project, Unity, or one of the two packages :

```
    "com.github.rostok.unitytoggletitlebar": "https://github.com/rostok/UnityToggleTitleBar.git",
    "com.marijnzwemmer.unity-toolbar-extender": "https://github.com/marijnz/unity-toolbar-extender.git",
```

**Comment by rostok** [comment]
will look into it when i install unity 6. if i remember correctly UnityToggleTitleBar depends on marijnzwemmer's extender.

**Comment by rostok** [comment]
Frankly I have no idea how to properly prepare this package so it can be installed painlessly. I think Unity doesn't support adding external GIT dependencies (which is stupid). So the only way is to do it exactly like you described by editing manifest.json. I have updated projects readme.
